sudo: required
services:
  - docker
before_install:
  - docker build -t dzontak/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run dzontak/react-test npm test -- --coverage
after_success:
  - docker build -t dzontak/multi-client ./client
  - docker build -t dzontak/multi-server ./server
  - docker build -t dzontak/multi-worker ./worker
  - docker build -t dzontak/multi-nginx ./nginx
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dzontak/multi-client
  - docker push dzontak/multi-server
  - docker push dzontak/multi-worker
  - docker push dzontak/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-2-784308828437
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
